### PR TITLE
fix(python example): Close channel to data server

### PR DESCRIPTION
**Pull request by smacker**
Currently open channels just hang there.

Ref: https://github.com/grpc/grpc/pull/15725

Signed-off-by: Maxim Sukharev <max@smacker.ru>

### CODE REVIEW

**Comment by smacker** [comment]
`with` statement is more pythonic. It should be always used if possible.
Sorry, no link for it but if you check [documentation](https://docs.python.org/3/library/os.html) for `os` modules for example, you will see that all examples use `with`.

**Comment by dpordomingo** [comment]
Yes, I saw it in the good reference you added in the PR desc, so lgtm :dagger: 
thanks for the double clarification :tada:

**Comment by dpordomingo** [comment]
example analyzers are now under `examples` dir; sorry :wink: 
I think once you solve the conflict @carlosms will agree if you merge the PR :crossed_swords:

**Comment by smacker** [comment]
Looks like it was already fixed by another PR.

**Pull request closed without merging**
