### PR TITLE
Use https remote in github repos

### PR DESCRIPTION
**Pull request by carlosms**
In order to apply github authentication the remote needs to be `https://` instead of `git://`. Context in https://github.com/src-d/lookout/pull/326.

### CODE REVIEW

**Comment by smacker** [comment]
I'm a little bit concerned about this change. It looks like a hack tbh.
At the same time I understand the need for it.

@smola what do you think?

**Comment by carlosms** [comment]
Ok, it's fair enough concern. Let me give some context.

The go-vcsurl parse method builds the clone url as `git://github.com/user/repo.git`
https://github.com/sourcegraph/go-vcsurl/blob/v1/vcsurl.go#L96

[GitHub docs](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended) say https is the recommended remote url:

> Cloning with HTTPS URLs (recommended)
> The https:// clone URLs are available on all repositories, public and private.

I'd say using `https://github.com/user/repo.git` is just as hack or as robust as what `go-vcsurl.Parse` is doing.

**Comment by smacker** [comment]
Oh. And `go-vcsurl` is archived repository. What do you think about forking it?

**Comment by smola** [comment]
AFAIK `git://` can be faster on public repositories and `https://` is just required for private repositories if using auth tokens.

With respect `vcsurl` are we actually using its output? I'm I bit worried that we are doing this:
```go
type RepositoryInfo = vcsurl.RepoInfo
```
attaching our gRPC protocol to symbol defined in an external+deprecated library

**Comment by carlosms** [comment]
Pinging @mcuadros to join the conversation. Since you left this TODO and maybe you had some ideas how to replace `vcsurl`.
https://github.com/src-d/lookout-sdk/blob/e06a088af4fe40561700c057c5dacd46e23b2abe/pb/event.go#L92

**Comment by smacker** [comment]
Reasons to remove `vcsurl`:
- external & deprecated
- containes only few special cases for some hosts. For example it handles gitlab incorrectly.
- for some providers username is empty but we rely on it in our code
- supports bzr, hg which we don't
- doesn't really check schema `git`, `https`, `http`, `wrong` all are valid. In our case, we can restrict only to `https`.

We can replace it with 1 simple function: https://play.golang.org/p/CVQ8Qa1XoQR
it's more opinionated (for example it assumes always git) but resolves all our issues. We can improve it later if needed but it don't think we will need it any time soon. Currently, we work only with github.

I propose to replace it with func linked above here in sdk and remove workaround from lookout.

**Comment by carlosms** [comment]
LGTM :+1:
But for the final implementation I'd add a check for the `Host` to be a known one before doing the split.

**Comment by carlosms** [comment]
Yes. My reasoning is that if we add support for something else, it will probably be better to have a bug because of empty `owner` and `name` than whatever happens to end in those fields.

**Comment by smacker** [comment]
superseded by https://github.com/src-d/lookout-sdk/pull/26

**Pull request closed without merging**
