### PR TITLE
Removes merge field from ReviewEvent and regenerates files

### PR DESCRIPTION
**Pull request by se7entyse7en**
First task from issue: https://github.com/src-d/lookout/issues/83.

### CODE REVIEW

**Comment by carlosms** [comment]
Looks like the code generated by you and by travis is different. Maybe there is a problem with the versions used.

**Comment by se7entyse7en** [comment]
@carlosms you're right, the version was wrong. Thanks!

**Comment by carlosms** [comment]
Maybe we should make the field [reserved](https://developers.google.com/protocol-buffers/docs/proto3#reserved)?

**Comment by se7entyse7en** [comment]
@carlosms I don't completely understand what is the case that would cause problems. AFAIU the problem arises if now we remove it and then let's say next week we add another field with the same name and number, but for example a different type. But that could be a problem if that object is interpreted using the old version of the proto file right?

**Comment by smacker** [comment]
imo we are still at the very early stage of lookout and pollute it with reserved doesn't make much sense to me.

**Comment by carlosms** [comment]
:man_shrugging: ok let's skip the reserved

**Pull request merged**
