### PR TITLE
Fix the top level __init__

### PR DESCRIPTION
**Pull request by vmarkovtsev**

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@smacker Some tests failed but they seem unrelated to this change.

**Comment by carlosms** [comment]
Is there a context for why the change is needed?

**Comment by vmarkovtsev** [comment]
This is a top level init which does not belong to this project and cannot contain custom code such as version. It is shared and does not belong to anyone.

**Comment by vmarkovtsev** [comment]
@smacker You've got sdk subir which is the perfect candidate for versions.

**Comment by smacker** [comment]
Yes. I put version inside sdk subdir. Let's wait for Carlos to review and merge both then. 👍

**Comment by carlosms** [comment]
Thank you for the explanation :+1:

**Pull request merged**
