### PR TITLE
 move DataClient from lookout to new sdk package 

### PR DESCRIPTION
**Pull request by smacker**
Lookout contains convenient wrapper for grpc data client.
It's meant to be used by analyzers, so only dummy analyzer uses it
currently.

This commit moves the wrapper into lookout-sdk to allow all analyzers
use it.

I put it into new `sdk` package which is higher level sdk for Go than
current pb. We also may reconsider which custom code belongs to pb and
move the rest into this package to separate low level auto generated
code from actual sdk API.

### CODE REVIEW

**Comment by se7entyse7en** [comment]
> We also may reconsider which custom code belongs to pb and
move the rest into this package to separate low level auto generated
code from actual sdk API.

I think that's a good idea! 👍

**Comment by se7entyse7en** [comment]
I also prefer having `./python` and `./go` instead of having go sdk in `./`. Currently, it seems that SDK for Python is some sort of second-class thing, but I don't think that this is the case (correct me if I'm wrong). So in the end we'll have:
- `proto` - common definitions,
- `python` - for python SDK,
- `go` - for go SDK.

**Comment by smacker** [comment]
I think `pb` directory should be inside `go`.
I didn't move it because it's breaking change.
How about if I move `sdk` into `go` here and for `pb` we do another PR combined it with moving some code from `pb` to `sdk`?

**Comment by carlosms** [comment]
sounds good to me

**Pull request merged**
